---
# handlers file for ansible-role-postgres-cluster
- name: restart patroni
  become: true
  systemd:
    name: "patroni"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart firewalld
  become: true
  service:
    name: firewalld
    state: restarted
